name: Draw keymap
on: [push, pull_request, workflow_dispatch]

jobs:
  draw:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - keymap: hypergolic
            layout_args: -k ferris/sweep
          - keymap: swweeep
            layout_args: -k crkbd/rev1 -l LAYOUT_split_3x5_3
    steps:
    - name: Checkout
      uses: actions/checkout@v3      
    - name: Draw with keymap-drawer
      run: | 
        python3 -m pip install keymap-drawer
        keymap parse -z ${GITHUB_WORKSPACE}/config/${{ matrix.keymap }}.keymap | keymap draw ${{ matrix.layout_args }} - >${{ matrix.keymap }}.svg
    - name: Upload SVGs
      uses: actions/upload-artifact@v3
      with:
        name: keymap_svgs
        path: '*.svg'
        retention-days: 7
